package com.ggalmazor.downsampling;

/**
 * Basic {@link Point} implementation backed by {@code double} values.
 *
 * <p>As a record, {@link DoublePoint} provides correct {@code equals}, {@code hashCode}, and
 * {@code toString} out of the box, and its accessor names ({@code x()}, {@code y()}) match the
 * {@link Point} interface directly without any override boilerplate.
 *
 * <p>The compact constructor is intentionally omitted: the record canonical constructor
 * generated by the compiler is sufficient.
 *
 * @param x the value of the point in the horizontal dimension (time)
 * @param y the value of the point in the vertical dimension
 */
public record DoublePoint(double x, double y) implements Point {

  /**
   * Utility factory for {@link DoublePoint} that accepts abstract {@link Number} values.
   *
   * @param x the value of the point in the horizontal dimension (time)
   * @param y the value of the point in the vertical dimension
   * @return the new {@link DoublePoint} instance
   */
  public static DoublePoint of(Number x, Number y) {
    return new DoublePoint(x.doubleValue(), y.doubleValue());
  }
}
